import re
p=open('main/trusted-local-handyman-services/handyman-service-near-me/index.html',encoding='utf-8').read()
body=re.search(r'<body[^>]*>(.*?)</body>',p,re.S).group(1)
body=re.sub(r'<(script|style|footer)[^>]*>.*?</\1>',' ',body,flags=re.S)
txt=re.sub(r'<[^>]+>',' ',body)
words=re.findall(r"[A-Za-z']+",txt)
print('words:',len(words))
h2_6=re.findall(r'<h[2-6][^>]*>(.*?)</h[2-6]>',body,re.S)
print('h2-6 elements:',len(h2_6))
hw=sum(len(re.findall(r"[A-Za-z']+",re.sub(r'<[^>]+>',' ',h))) for h in h2_6)
print('h2-6 words:',hw)
ps=re.findall(r'<p[^>]*>(.*?)</p>',body,re.S)
print('p elements:',len(ps))
pw=sum(len(re.findall(r"[A-Za-z']+",re.sub(r'<[^>]+>',' ',x))) for x in ps)
print('p words:',pw)
strongs=re.findall(r'<(strong|b)[^>]*>(.*?)</\1>',body,re.S)
print('strong/b elements:',len(strongs))
sw=sum(len(re.findall(r"[A-Za-z']+",re.sub(r'<[^>]+>',' ',s[1]))) for s in strongs)
print('strong/b words:',sw)
for ph in ['handyman services','home repair services','repair services','maintenance services','handyman service','handyman professionals','home improvement projects','home repairs','other services','home improvement','get the job done','completely free','to do list','free quotes','small jobs','fixing things','great communication','done right','around your home','take care','first time']:
    print(f'{ph:35} {len(re.findall(ph,txt,re.I))}')
